### ISSUE TITLE
Lr atarken beacon çıkması

### ISSUE THREAD

**Issue by ghost** [emreires/Gelismis-LR-Plugini#1]
Sm hosties de ki gibi lr atan kişiyle atılana beacon verse sonra bitince kaldırsa efsane olabilir

**Comment by emreires** [comment]
Normal beacon vermeyi yaparsak ses müzikle karışabilir diye eklememiştim. O beep beep sesi :)

İsterseniz LR atarken sm_beacon ile bir deneyin dönüş yaparsınız buradan problem olmuyorsa.

**Comment by ghost** [comment]
@emreires kodlama bilgim çok yok ama sm_beacon da tek tek konsoldan yazmak saçma olur diye düşündüm. Müziksiz lr atmak istiyoruz da biz müziği sildik beacon eklenebilir mi acaba eklense efsane olur plugin çünkü

**Comment by emreires** [comment]
#https://github.com/emreires/Gelismis-LR-Plugini/commit/051350f23051dc209a3ad866ef50d500c98bae92

Eklenmiştir.
